stages:

  - iac_validate
  - iac_plan
  - iac_apply
  - app_deploy
  

default:
  image:
    name: google/cloud-sdk:latest
    
  before_script:
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt-get install software-properties-common -y
    - apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - apt-get update -y
    - apt install terraform -y
    - terraform init
  cache:
    key: terraform
    paths:
      - .terraform



Terraform Plan:
  stage: iac_plan
  script: 
    - terraform plan --out plan
  only:
    refs:
      - master
  artifacts:
    paths:
      - plan

Terraform Apply:
  stage: iac_apply
  script:
    
    - terraform apply --auto-approve plan
  when: manual
  allow_failure: false
  only:
    refs:
      - master
  
  

Deployment GKE Apps:
  image:
    name: google/cloud-sdk:latest
  stage: app_deploy   
  script:
    - gcloud auth activate-service-account --key-file=$GCP_KEY
    - gcloud container clusters get-credentials terraform --zone us-west1-b --project  perceptive-net-319104
    - kubectl apply -f Deployments/mongo.yaml
    - kubectl apply -f Deployments/nodeapp.yaml
  when: manual
    
    

  